# DOCS BEGIN #
# Commands:
#  - /tafk <wand/save/reload/item> (aliases: /afk)
#  - /silentgive {player} <item> <amount>(optional, by default it's 1)
#    -> (if you use this inside commands to give to afk players, you can even give NBT items too!)
#    -> (if you want to give custom items from the items(configuration section) you will need to put the name inside { }
#    -> e.g.: /sgive {player} {test3} 2
# DOCS END #
check_for_update: true # if a new update on spigot is released, you'll get a message in console and ingame
default_afk_time: 1200 # in seconds
afk_times: # name of permissions here
  default: 1200 # in seconds
region:
  locations:
    world: world
    loc1:
      x: x
      y: y
      z: z
    loc2:
      x: x
      y: y
      z: z

# MESSAGES AND SOME CONFIGURATIONS ABOUT REGION
show_xp_bar: true # when player is inside region it will show them (BETA)
silent_player_inventory_full: "&cYour inventory is full, therefore you will not receive anything!"
actionbar:
  show: false
  messages:
    sg_day: " day, "
    pl_day: " days, "
    sg_hour: " hour, "
    pl_hour: " hours, "
    sg_minute: " minute, "
    pl_minute: " minutes, "
    0_seconds: " Resetting!"
    sg_second: " second."
    pl_second: " seconds."
    before_msg: "{player} has been afk for >> "

commands: # silent commands: use sgive to give players items without showing anything in console
          # btw, ONLY with sgive you will be able to give items with NBT tags if players are afk
          # usage: /silentgive (or sgive) {player} (if it's consolesender then you can put the name from items inside {})
  - "msg {player} you were afk!"
  - "eco give {player} 100"
  - "silentgive {player} {test3}"
items:
  test3:
    ==: org.bukkit.inventory.ItemStack
    v: 3218
    type: NETHERITE_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"italic":false,"color":"red","text":"TESTING"}],"text":""}'
      Unbreakable: true
