check_for_update: true
default_afk_time: 1200
afk_times: # rank parents here
  default: 1200
region:
  locations:
    world: world
    loc1:
      x: x
      y: y
      z: z
    loc2:
      x: x
      y: y
      z: z
commands:
  - "msg {player} you were afk!"
  - "eco give {player} 100"