name: ToastedAFK
version: '${project.version}'
main: me.serbob.toastedafk.ToastedAFK
api-version: 1.19
authors: [ Serbob ]
softdepend: [LuckPerms, Multiworld, Multiverse-Core]
description: An afk plugin.
commands:
  afkwand:
    description: Gives you a wand to specify the region where the players should receive their rewards.
  afksave:
    description: Save the positions made with the AFK Wand (pos1 and pos2)
permissions:
  afk.update:
    default: op
  afkwand.use:
    default: op
  afksave.allow:
    default: op