name: ToastedAFK
version: '${project.version}'
main: me.serbob.toastedafk.ToastedAFK
api-version: 1.19
authors: [ Serbob ]
softdepend: [LuckpermsAPI]
description: An afk plugin.
depend: [WorldGuard]
permissions:
  afk.update:
    default: op