name: ToastedAFK
version: '${project.version}'
main: me.serbob.toastedafk.ToastedAFK
api-version: 1.13
authors: [ Serbob ]
softdepend: [Multiworld, Multiverse-Core]
description: An afk plugin.
commands:
  tafk:
    description: AFK Commands.
  silentgive:
    description: Silent give.
    aliases:
      - sgive
permissions:
  afk.update:
    default: op
  afk.wand:
    default: op
  afk.save:
    default: op
  afk.reload:
    default: op
  afk.item:
    default: op
  silentgive.use:
    default: op